services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
    restart: unless-stopped
    network_mode: host
  timesync:
    build: ./timesync
    container_name: timesync_publisher
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_TOPIC=lagerbuzzer/time_sync
      - INTERVAL_MS=5000
    depends_on:
      - mosquitto
    restart: unless-stopped
    network_mode: host
  webserver:
    build: ./webserver
    container_name: webserver
    ports:
      - "5000:5000"
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_BUZZ_TOPIC=lagerbuzzer/buzz
      - WEB_PORT=5000
    depends_on:
      - mosquitto
    restart: unless-stopped
    network_mode: host
